# Generated by Django 4.2.2 on 2023-06-15 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0002_alter_receipe_ingredient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipe',
            name='ingredient',
        ),
        migrations.AlterField(
            model_name='receipeingredient',
            name='amount',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='receipeingredient',
            name='ingredient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='container.ingredient'),
        ),
        migrations.AlterField(
            model_name='receipeingredient',
            name='receipe_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='container.receipe'),
        ),
    ]
