# Generated by Django 4.2.2 on 2023-06-16 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0003_remove_receipe_ingredient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipeingredient',
            name='ingredient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_detail', to='container.ingredient'),
        ),
        migrations.AlterField(
            model_name='receipeingredient',
            name='receipe_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_receipe', to='container.receipe'),
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('procedure_id', models.AutoField(primary_key=True, serialize=False)),
                ('step_number', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField()),
                ('receipe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedure_receipe', to='container.receipe')),
            ],
        ),
    ]
